#define SYS_test         0
#define SYS_print        1
#define SYS_brk          2
#define SYS_open         3
#define SYS_close        4
#define SYS_fork         5
#define SYS_wait         6
#define SYS_exit         7
#define SYS_sleep        8
#define SYS_kill         9
#define SYS_getpid       10
#define SYS_read         11
#define SYS_write        12
#define SYS_mkdir        13
#define SYS_link         14
#define SYS_unlink       15
#define SYS_fstat        16
#define SYS_dup          17
#define SYS_setprior     18
#define SYS_getprior     19
#define SYS_yield        20